# Render.com デプロイ設定
services:
  - type: web
    name: video-merger-tool
    runtime: docker
    plan: free  # または starter ($7/月)
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MAX_FILE_SIZE
        value: 500000000  # 500MB
    disk:
      name: video-storage
      mountPath: /app/data
      sizeGB: 1  # 無料プランは1GB