name: Simple Test

on:
  push:  # プッシュごとに実行
  workflow_dispatch:  # 手動実行ボタン

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Test
      run: |
        echo "✅ GitHub Actions is working!"
        python3 --version
        ls -la
        echo "Current time: $(date)"